### PR TITLE
Report generation improvement work 4

### PR DESCRIPTION
**Pull request by shigeya**
- Using wider table style (100em) for readability
- In the report by methods section, all rows now with statement texts.
- Minor adjustments on stylesheets
- Added descriptions for clippings of longer strings
- Hyperlinks with statements.

### CODE REVIEW

**Comment by shigeya** [comment]
I realized that hyperlinks from Sec.3.3 is missing. I will add the feature to this PR quickly.

**Comment by shigeya** [comment]
Found major problem, so close this for now.

**Comment by shigeya** [comment]
Verified that it's working. Please review.

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
@shigeya thank you for this PR!

**Review by peacekeeper — APPROVED** [review]

**Review by msporny — APPROVED** [review]

**Pull request merged**
