### PR TITLE
Add did:3 from 3Box Labs

### PR DESCRIPTION
**Pull request by oed**
Had to update the `did-core-properties` test because some tests were failing even though the properties are optional.

~Also, it looks like the did-resolution tests changed to expect a different format. Should I add a separate json file for that test?~

Edit:

Fixed two bugs in the did-resolution tests.

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
@oed 

> Should I add a separate json file for that test?

yes, we're trying to allow folks to show conformance to parts of the spec without asking them to show conformance to all of it at once.

**Comment by oed** [comment]
Ok, I'll update the PR, thanks @OR13.

**Review by OR13 — APPROVED** [review]

**Comment by msporny** [comment]
@oed -- the data model for the input documents is going to be changing soon: https://github.com/w3c/did-test-suite/pull/55 -- I hesitate to pull this in now (and then have it immediately fail).

I'm going to hold this until after the weekend and then ask you to rebase and change the input files. Other than that, everything looks fine; you just caught us while we were making some fundamental changes to the input files. I don't expect the rebase to create too much headache for you.

**Comment by oed** [comment]
Ok, thanks for the heads up @msporny. Hopefully #55 gets merged soon :)

**Comment by msporny** [comment]
> Ok, thanks for the heads up @msporny. Hopefully #55 gets merged soon :)

Alright, @oed merged and ready for you to rebase on `main`.

Pay particular attention to the new implementation file format, namely these lines:

https://github.com/w3c/did-test-suite/blob/main/packages/did-core-test-server/suites/implementations/did-key-2020-db.json#L11-L12

and

https://github.com/w3c/did-test-suite/blob/main/packages/did-core-test-server/suites/implementations/did-key-2020-db.json#L41-L42

Let me know if you hit any issues... happy to help.

**Comment by oed** [comment]
Thanks @msporny updated the PR!

**Review by msporny — APPROVED** [review]

**Pull request merged**
