### PR TITLE
feat: add did-kilt-2021

### PR DESCRIPTION
**Pull request by Diiaablo95**
# Kilt DID method specification

Kilt DID method specification test according to the [GitHub thread](https://github.com/w3c/did-test-suite/issues/89).

## Fixes https://github.com/KILTprotocol/ticket/issues/1293

### CODE REVIEW

**Comment by msporny** [comment]
ETA on this PR being done, @Diiaablo95 ?

**Comment by Diiaablo95** [comment]
Hey @msporny, it is currently blocked by https://github.com/w3c/did-test-suite/issues/99, which I opened a while ago. Do you perhaps have suggestions?

**Comment by msporny** [comment]
@Diiaablo95 ... I'm currently trying to get the other implementers to fix some of their broken tests before trying to debug your issue.

**Comment by Diiaablo95** [comment]
@msporny I had to focus on other tasks in the past week, so I did close to zero work for this one. Some more details about the problem are mentioned in https://github.com/w3c/did-test-suite/issues/99. As a non-JS expert, that is as far as I could go without spending too much time on the problem (time that I did not have).

**Pull request merged**
