### PR TITLE
did-jnctn test config

### PR DESCRIPTION
**Pull request by pete-smith-jnctn-nz**
1.  Added did:jnctn input file(s) to the implementations directory. 
2.  Add did:jnctn input file to did-identifier, did-core-properties, did-production  
3.  Run the test suite which passes.
4.  Submit this pull request on this repository

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
please resolve merge conflict

**Comment by pete-smith-jnctn-nz** [comment]
Hi @OR13, that should be good now

**Review by msporny — APPROVED** [review]
Please resolve merge conflicts.

**Comment by kdenhartog** [comment]
Noting we've got a package-lock.json file in there already. I couldn't figure out why the new one is in there.

**Comment by pete-smith-jnctn-nz** [comment]
Thanks for spotting the package-lock.json @kdenhartog  - I think the best bet is for me to do a fresh PR that's clean

**Pull request closed without merging**
