### PR TITLE
Temporary Workaround to make test pass

### PR DESCRIPTION
**Pull request by shigeya**
Recently merged commit causing a lot of failure for jest CLI run
(i.e., `npm run test`)

Following files' universal resolver related implementation JSON
files `require`s commented out to make the test pass:
	suites/did-consumption/default.js
	suites/did-production/default.js
	suites/did-resolution/default.js

### CODE REVIEW

**Comment by peacekeeper** [comment]
I don't think we should be deactivating implementation reports just because they are failing. It's okay if some tests are failing.

We should encourage the implementers to update their reports, and/or fix the tests themselves (as you suggest in https://github.com/w3c/did-test-suite/issues/111).

**Comment by shigeya** [comment]
Yes, I understand. As I wrote in the subject, this is a temporary fix, so it might not be necessary as a PR.

I created this PR because I can show how I can silence errors which might be useful to find issues.
For me, I can use this commit to continue work on my report generator.

**Comment by msporny** [comment]
Merge conflicts, please fix, @shigeya.

**Comment by shigeya** [comment]
@msporny done. merged, then temporarily suspended (commented) some tests.

**Comment by msporny** [comment]
> We should encourage the implementers to update their reports, and/or fix the tests themselves 

Currently failing tests are from:

* Universal resolver (@peacekeeper @BernhardFuchs)
* did:unisot (@mirkostanic)
* did:vaa (@caict-develop-zhangbo)
* did:key (@msporny)
* did:v1 (@msporny)

Everyone listed above, please fix your tests... they are causing failures in the test suite that are confusing other implementers.

**Comment by shigeya** [comment]
> Everyone listed above, please fix your tests... they are causing failures in the test suite that are confusing other implementers.

We may want to have the following two configs for mitigation of the situation:

- Default test configuration file which verified to pass all of the tests.
- Experimental configuration file which may fail on some of the tests.

To do this, we need to move the configuration which refers to implementations (`*/defaults.js`) into site-config.js (which passes all of the tests) and creates `site-config-all.js` which includes all of the implementations. Then ask implementers to add their implementations to `site-config-all.js`. We verify the test result then merge the tested new implementations to `site-config.js`

**Comment by shigeya** [comment]
Updated to use the latest main branch.

**Comment by BernhardFuchs** [comment]
@shigeya Just ran the testsuite from main for did-resolution and the only failures are for `did:ccp`. We are aware of them https://github.com/decentralized-identity/uni-resolver-driver-did-ccp/issues/5 but have no concrete timeline yet.  

If there are issues with universal-resolver-did-{unisot,v1,vaa,web,work} can you pls show how to reproduce them.

**Comment by shigeya** [comment]
> If there are issues with universal-resolver-did-{unisot,v1,vaa,web,work} can you pls show how to reproduce them.

You're right. There is something wrong with the test code.

By following these steps:

1. Check out the main branch.
2. at the top-level of the repository, run: `lerna run prepare`  (to make sure all of the matchers are available)
3. run `jest` at the top-level.

creates this output:
> Test Suites: 19 failed, 19 total
> Tests:       1024 failed, 33 todo, 1861 passed, 2918 total
> Snapshots:   0 total
> Time:        7.018 s

The whole output is in [this gist](https://gist.github.com/shigeya/b7d6a8afbb699b28a460978858f45ff0)

now, I found that run `npm run jest` (which is the official way to run the test) shows a different set of errors:

(jest-did-matcher part skipped)
> did-core-test-server: Test Suites: 4 failed, 2 passed, 6 total
> did-core-test-server: Tests:       10 failed, 33 todo, 2889 passed, 2932 total
> did-core-test-server: Snapshots:   0 total
> did-core-test-server: Time:        6.012 s
> did-core-test-server: Ran all test suites.

The output for this run is in [this gist](https://gist.github.com/shigeya/ffbd5b07c754eab2edac5dbf7baab525)

Strange. A curious part of this result is the total numbers of tests are different. And these are only happening with the above-mentioned universal resolver cases. I will look into this issue tomorrow.

Anyway, running test 'official way' still causes errors with universal resolver case with `ccp`.

**Comment by BernhardFuchs** [comment]
Ad approach 1) There are tests in `jest-did-matchers` package too, so my assumtion is that they contribute as the additional testcases. The difference is that they are midfixed `test` [see](https://github.com/w3c/did-test-suite/blob/main/packages/jest-did-matcher/src/matchers/toBeDidDocumentPropertyValueType/index.test.js)  

Ad approach 2) That's the same results we get when running the testsuite manually. Under the hoot it runs `lerna run test --stream`, which is probably configured to run `spec` files only.   

I usually run `npm run test` on package level of `did-core-test-server`, which also works fine.

**Comment by OR13** [comment]
Failing tests are not a bad thing, as long as the report it functioning.

Is the report JSON functional? if so, I suggest we merge the PR and let failures be addressed in subsequent PRs.

**Review by OR13 — APPROVED** [review]

**Comment by shigeya** [comment]
> Failing tests are not a bad thing, as long as the report is functioning.
> 
> Is the report JSON functional? if so, I suggest we merge the PR and let failures be addressed in subsequent PRs.
> 
> If this PR is needed to make the report generation (with failures and passes) functional it should be merged ASAP.

I agree, but as @msporny said, errors confuse implementers to test whether the errors come from their implementations or other reasons. We need a way to communicate with implementers that what are current `normal` statuses.

**Comment by OR13** [comment]
@shigeya yes, I struggled with this...

I think all we need to do is add a warning to the readme, that any errors in sections of the spec not related to your implementation must be ignored, and that some test are expected to fail, and that implementors need only focus on their tests.

**Comment by shigeya** [comment]
@OR13 Maybe, as part of the report generation, we may add a summary for implementers to see whether their tests are failing.

Unfortunately, I don't have time to work on this now (today or tomorrow). Maybe on Thursday.

**Comment by caict-develop-zhangbo** [comment]
> Updated to use the latest main branch.
> 
> Currently failing the followings:
> 
> * did-consumption: unisot, vaa
> * did-core-properties: orb
> * did-production: unisot, vaa
> * did-resolution: ccp, universal-resolver-did-{unisot,v1,vaa,web,work}

@shigeya I'll fix it as soon as possible

**Comment by caict-develop-zhangbo** [comment]
> > We should encourage the implementers to update their reports, and/or fix the tests themselves
> 
> Currently failing tests are from:
> 
> * Universal resolver (@peacekeeper @BernhardFuchs)
> * did:unisot (@mirkostanic)
> * did:vaa (@caict-develop-zhangbo)
> * did:key (@msporny)
> * did:v1 (@msporny)
> 
> Everyone listed above, please fix your tests... they are causing failures in the test suite that are confusing other implementers.

 @shigeya @msporny I'll fix it as soon as possible

**Comment by OR13** [comment]
@shigeya this now has conflicts, is this still necesssary?

**Comment by shigeya** [comment]
@OR13 You're right. I think not necessary anymore. Closing.

**Pull request closed without merging**
