### PR TITLE
Add Evernym did:web report

### PR DESCRIPTION
**Pull request by talltree**
This is a report for a DID created internally at Evernym to demonstrate the use of alsoKnownAs.

### CODE REVIEW

**Comment by msporny** [comment]
> This is a report for a DID created internally at Evernym to demonstrate the use of alsoKnownAs.

Is there public code that demonstrates the implementation of this feature?

**Comment by talltree** [comment]
@msporny Since the `did:web` method relies on a DID document posted to an HTTPS server, the implementation code is the resolver. [This particular implementation report used the DIF Universal Resolver](https://dev.uniresolver.io/#did:web:evernym.com), however if needed I could submit other implementation reports using other resolvers.

**Comment by msporny** [comment]
> @msporny Since the `did:web` method relies on a DID document posted to an HTTPS server, the implementation code is the resolver. [This particular implementation report used the DIF Universal Resolver](https://dev.uniresolver.io/#did:web:evernym.com), however if needed I could submit other implementation reports using other resolvers.

Thanks, helpful, that's all we need, AFAIK:

1. Evernym created a DID Document that used `alsoKnownAs` and resolved it through the Universal Resolver (#187).
2. Danube Tech created a DID Document that used `alsoKnownAs` using libraries and APIs from the EBSI Early Adopter program (#186).

That is two independent implementations that have demonstrated support for `alsoKnownAs`.

I'll merge both to the test suite tomorrow, and remove the at risk issue marker for `alsoKnownAs`. :)

**Comment by talltree** [comment]
Thanks Manu.

**Comment by kdenhartog** [comment]
Nice, thanks @talltree for getting an implementation in for this feature. I think this is a good example of it as well to show how it can be used for non-did based URIs as well.

**Review by kdenhartog — APPROVED** [review]

**Pull request merged**
