### PR TITLE
Add scenarios for DID syntax

### PR DESCRIPTION
**Pull request by peacekeeper**
FYI I've been experimenting with adding tests for DID syntax, but I'm sure this is not yet ready to merge.

### CODE REVIEW

**Review by OR13 — COMMENTED** [review]
These look good!

**Comment by OR13** [comment]
@peacekeeper can we clean this up and get it merged?

**Comment by peacekeeper** [comment]
@OR13 I just converted this from draft PR to real PR. I guess we could merge this in order to have some progress, and then improve/refactor later?

**Comment by OR13** [comment]
merging this ahead of refactoring

**Pull request merged**
