### PR TITLE
Add entries for did:ion

### PR DESCRIPTION
**Pull request by csuwildcat**
I ran the tests and the generated report shows failures for the following:

1. 5.x Core Properties - not accepting relative paths (`#some-id`) as valid entries for key identifiers
2. 5.x Core Properties - controller field not allowed to be blank in key descriptor, even though JSON-LD populates it, and the base URI assumption should hold (we can modify our stuff, but it's just a bit wonky that base URI doesn't carry here)
3. 7.3 Metadata Structure - 2x instances of failure on this, but no clue why this is failing, or what it even means: `Tests cannot be nested. Test "7.3 Metadata Structure - The structure used to communicate this metadata MUST be a map of properties."`

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 26, 2021, 3:22 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fcsuwildcat%2Fdid-test-suite%2Fdf8d2d2dec4b754a6f4edf3ff6aa2cca4bc91512%2Findex.html%3FisPreview%3Dtrue)

```
📡 HTTP Error 404: https://rawcdn.githack.com/csuwildcat/did-test-suite/df8d2d2dec4b754a6f4edf3ff6aa2cca4bc91512/index.html
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/did-test-suite%23120.)._
</details>

### CODE REVIEW

**Comment by csuwildcat** [comment]
I would love clarification on the specific directives around the base URI of the DID document, and what we are supposed to do to if we want to use a relative URL that leverages the base URI of a DID Document.

**Comment by shigeya** [comment]
@csuwildcat I addressed issues in Sec 7.3 in PR #122, it was not property work for nested map/array objects.

**Comment by shigeya** [comment]
The remaining errors are:
1. Current test code only allows a full DID URL, not a relative DID URL. Verification Method's ID value should allow relative DID URL.
2. "controller" value needs to be non-empty, but it's empty.

I created a PR #123 to address this.

**Comment by msporny** [comment]
@csuwildcat, merge conflicts, please fix.

**Comment by OR13** [comment]
@csuwildcat please resolve merge confs

**Comment by csuwildcat** [comment]
@OR13 should those output files be gitignored?

**Comment by msporny** [comment]
@csuwildcat please remove `index.html` and `test-vectors/did-spec.latest.json` -- we are no longer tracking autogenerated files in the github repo... they will be produced on a Github Action / nightly build basis going forward.

**Review by msporny — CHANGES_REQUESTED** [review]
@csuwildcat please remove index.html and test-vectors/did-spec.latest.json -- we are no longer tracking autogenerated files in the github repo... they will be produced on a Github Action / nightly build basis going forward.

**Comment by csuwildcat** [comment]
@msporny everything appears to be in order now, so can we please merge while there are no conflicts?

**Comment by csuwildcat** [comment]
5b0v2y

**Pull request merged**
