### PR TITLE
add art method

### PR DESCRIPTION
**Pull request by ArtracID**
Create did:art method for art collection identity

### CODE REVIEW

**Comment by ArtracID** [comment]
Create did:art method for art collection identity

**Review by OR13 — APPROVED** [review]

**Comment by ArtracID** [comment]
Hello W3C examiners.
Just to reconfirm we are still in the DID application process =) never give up

**Comment by OR13** [comment]
@ArtracID thanks for the ping!

**Comment by ArtracID** [comment]
Great. Thank you

**Pull request merged**
