### PR TITLE
Report Generator Work - Part 2

### PR DESCRIPTION
**Pull request by shigeya**
Refactored part of the report generator code, then added a summary section.

Detailed page's design changed also:
- method name included, implementation now has own column
- Each of the lists sorted by the method name in alphabetical order.
- Very long DIDs in the parameter section are clipped and replaced with ellipses.

Scripts splitted into two:
- `npm run generate-test-data`  runs test and store JSON data.
- `npm run generate-report` read the JSON and updates the report (currently index.html)
- `npm run test-and-generate-report` runs test then generate the report

The design elements discussed at the last week's call are not fully implemented yet.

The codes are not clean and not final.  Refactoring and elimination of duplicates needed.
I will do that later.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 28, 2021, 2:04 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fdid-test-suite%2Fcff8582b95ffa89ae5fd92b7a5255f989c5014d9%2Findex.html%3FisPreview%3Dtrue)

```
📡 HTTP Error 404: https://rawcdn.githack.com/w3c/did-test-suite/cff8582b95ffa89ae5fd92b7a5255f989c5014d9/index.html
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/did-test-suite%23138.)._
</details>

### CODE REVIEW

**Comment by shigeya** [comment]
It is mergeable now. Still lacks some feature but the latest version is useful enough for developers.

Once `index.html` is resurrected, I will resolve conflicts.

**Comment by shigeya** [comment]
Sneak preview of the summary I added:

ScreenShot 2021-05-28 8 51 23

**Review by msporny — CHANGES_REQUESTED** [review]
Overall, looks like good progress, thank you @shigeya.

Can you please remove `index.html` and `did-spec-test-run.latest.json`... we shouldn't be checking in auto-generated files into the repository.

**Comment by shigeya** [comment]
> Overall, looks like good progress, thank you @shigeya.

good.

> Can you please remove `index.html` and `did-spec-test-run.latest.json`... we shouldn't be checking in auto-generated files into the repository.

@msporny I can remove the JSON file without issue. But if I remove index.html from the commit, the program can't create the index.html from scratch. The report generator creates tables then replaces these tables in the section with the same ID in the index.html file. The texts other than tables stay the same. I need a template document somewhere in the repository. 

Are there any suggestions to do this?

**Comment by msporny** [comment]
> I need a template document somewhere in the repository.
> 
> Are there any suggestions to do this?

Yes, understood. I suggest naming the template file something that is not `index.html`, perhaps something like `report-template.html`. That template file should probably be placed near the report generation code, so perhaps in `packages/did-core-test-server/reports/` with `generate-latest-respec-data.js` moved to that directory as well.

**Comment by shigeya** [comment]
@msporny Updated. Please check. The result will be placed at `packages/did-core-test-suite/report/index.html`, temporary file is placed at `packages/did-core-test-suite/report/tmp` both of the paths are marked local .gitignore file

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
LGTM, can we merge @shigeya ?

**Comment by shigeya** [comment]
> LGTM, can we merge @shigeya?

No breaks for the other parts, tests run without raising runtime exceptions, the summary part is already useful and other works should be incremental.

I think it's good to merge now.

**Comment by msporny** [comment]
> I think it's good to merge now.

Thank you @shigeya -- I really appreciate all of the improvements you've made to the reporting functionality... it's really helped us figure out what is implemented and what isn't.

**Comment by msporny** [comment]
> The codes are not clean and not final. Refactoring and elimination of duplicates needed.
> I will do that later.

@shigeya, I had to add a few features to the report in order to make summarizing if we had enough independent implementations more automatic. These features include:

* Removing the example implementation from the feature displays and totals.
* Adding a number of independent implementations field to the table.
* Adding a warning if there were not enough independent implementations.

This was done in 22134989e76238356fe2f02354947a2ae865eb2b. Apologies as it was a bit hacky and I was in a rush. Happy for things to get refactored properly. Just letting you know that I did some of this work already.

**Comment by shigeya** [comment]
@msporny Thanks let me know. No problem at all.

**Pull request merged**
